#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Preprocess the raw Lotterywest CSV history into a compact data.js that the
static web app embeds directly (so the app works by opening index.html, no
server / no network required).

Outputs draws NEWEST FIRST. Only keeps draws matching the *current* game
format (so statistics reflect the rules in force today):
  - Oz Lotto : 7 main numbers 1-47, 3 supplementary 1-47
  - Powerball: 7 main numbers 1-35, 1 Powerball 1-20
"""
import csv, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
HIST = os.path.join(HERE, "history_results")
OUT  = os.path.join(HERE, "app", "data.js")


def to_int(v):
    try:
        return int(float(v))
    except (ValueError, TypeError):
        return None


def parse_oz(path):
    """Oz Lotto CSV is oldest-first. Cols: 0 draw#,1 date,2 iso,
    3-9 main 1..7, 10-12 supp 1..3."""
    rows = list(csv.reader(open(path, encoding="utf-8-sig")))
    out = []
    for r in rows[1:]:
        if len(r) < 13:
            continue
        main = [to_int(r[i]) for i in range(3, 10)]
        supp = [to_int(r[i]) for i in range(10, 13)]
        if any(x is None for x in main) or any(x is None for x in supp):
            continue
        # current format only
        if max(main + supp) > 47 or len(main) != 7 or len(supp) != 3:
            continue
        out.append({
            "n": to_int(r[0]),
            "date": r[2] or r[1],
            "main": main,
            "extra": supp,
        })
    out.sort(key=lambda d: d["date"], reverse=True)  # newest first
    return out


def parse_pb(path):
    """Powerball CSV is newest-first. Cols: 0 draw#,1 iso,2 orig,
    3-9 main 1..7, 10 powerball."""
    rows = list(csv.reader(open(path, encoding="utf-8-sig")))
    out = []
    for r in rows[1:]:
        if len(r) < 11:
            continue
        main = [to_int(r[i]) for i in range(3, 10)]
        pb = to_int(r[10])
        if any(x is None for x in main) or pb is None:
            continue
        # current format only: 7 main 1-35, powerball 1-20
        if len(main) != 7 or max(main) > 35 or pb > 20:
            continue
        out.append({
            "n": to_int(r[0]),
            "date": r[1],
            "main": main,
            "extra": [pb],
        })
    out.sort(key=lambda d: d["date"], reverse=True)
    return out


def main():
    oz = parse_oz(os.path.join(HIST, "australia_oz_lotto_tuesday_results_1994_to_2026_full.csv"))
    pb = parse_pb(os.path.join(HIST, "australia_powerball_results_1996_to_2026_full.csv"))

    data = {
        "ozlotto": {
            "name": "Oz Lotto",
            "rules": {"mainCount": 7, "mainMax": 47, "extraCount": 3,
                      "extraMax": 47, "extraName": "Supplementary",
                      "extraFromMain": True},
            "draws": oz,
        },
        "powerball": {
            "name": "Powerball",
            "rules": {"mainCount": 7, "mainMax": 35, "extraCount": 1,
                      "extraMax": 20, "extraName": "Powerball",
                      "extraFromMain": False},
            "draws": pb,
        },
    }

    js = "// Auto-generated by build_data.py — do not edit by hand.\n"
    js += "window.LOTTO_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"Oz Lotto current-format draws: {len(oz)} "
          f"(newest {oz[0]['date']} #{oz[0]['n']})")
    print(f"Powerball current-format draws: {len(pb)} "
          f"(newest {pb[0]['date']} #{pb[0]['n']})")
    print(f"Wrote {OUT} ({os.path.getsize(OUT)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
